docs: second drop of documentation on slz
terraform-ibm-modules/terraform-ibm-landing-zone pull request #123
Opened 2022-10-05 17:29 UTC by vburckhardt

### Description

Extra documentation on customization, client-to-site and teleport options

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

2022-10-05 21:41 UTC, SirSpidey requested changes
I think we should keep the docs folder visible (remove preceding `.`). But you'll have to update links (e.g. `./.docs/`)

The root Readme seems to repeat some things that I've fixed (Like Headings in Title Case).

I did not review this carefully. I have just noted the obvious.

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +You can't set both `create_f5_network_on_management_vpc` to true and set `teleport_management_zones` to a value greater than `0`.
```suggestion
Don't set both `create_f5_network_on_management_vpc` to true and `teleport_management_zones` to a value greater than `0`.
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +More information in regards to the meaning of each Teleport configuration variable can be found within the documentation for the pattern:
```suggestion
For more information about the Teleport configuration variables, see the following documentation for the pattern:
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +Once App ID has been successfully configured to teleport, you can log in to teleport through a web console or tsh client. Tsh is the Teleport client tool which is the command line tool for teleport.
```suggestion
After App ID is successfully configured to Teleport, you can log in to Teleport through a web console or tsh client. tsh is the Teleport client tool that is the command line tool for Teleport. For more information, see [Installing tsh](https://goteleport.com/docs/server-access/guides/tsh/#installing-tsh). You need the fully qualified domain name (FQDN) of the Teleport server to log in.
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +### Log In through the Web Console
```suggestion
### Log in through the web console
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +1. Access the web console on port 3080. ```https://<User defined FQDN of teleport server>:3080```
```suggestion
1. Access the web console on port 3080. (`https://<User defined FQDN of teleport server>:3080`)
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +### Log In through the Tsh Client
```suggestion
### Log in through the tsh client
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +## Debbuging Bastion Host VSI
```suggestion
## Debuging the bastion host VSI
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +After the bastion host is provisioned by the Secure Landing Zone, and you can't access Teleport that is installed on your virtual server, follow these steps to login and verify the configuration of y
```suggestion
After the bastion host is provisioned by the Secure Landing Zone, if you can't access Teleport that is installed on your virtual server, follow these steps to log in and verify the configuration of your virtual server through SSH.  SSH is not allowed by default, so you need to add rules to the [security groups](https://cloud.ibm.com/vpc-ext/network/securityGroups) and [ACLs](https://cloud.ibm.com/vpc-ext/network/acl) on our virtual server.
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +## ACL and Security Groups
```suggestion
## ACL and security groups
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/bastion/bastion.md
> +By default, Secure Landing Zone provisions ACL's and Security Groups that are more open and non-customer dependent.  Please utilize [override.json](../../README.md#using-overridejson) file to manipul
```suggestion
By default, Secure Landing Zone provisions ACLs and security groups that are more open and non-customer dependent.  Use the [override.json](../../README.md#using-overridejson) file to configure the add and delete rules for your environment.
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/f5-big-ip/f5-big-ip.md
> +## Prerequisites
```suggestion
## Before you begin
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +# Customizing Your Environment
```suggestion
# Customizing your environment
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +## Using terraform input variables
```suggestion
## Using Terraform input variables
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +### Supported Variables
```suggestion
### Supported variables
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +### Overriding Variables
```suggestion
### Overriding variables
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +### Overriding Only Some Variables
```suggestion
### Overriding only some variables
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
> +# Secure Landing Zone Module: Details
```suggestion
## Secure Landing Zone module details
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
>  ## VPC
```suggestion
### VPC
```

2022-10-05 21:41 UTC, SirSpidey commented on README.md
>  ### vpcs variable
```suggestion
#### vpcs variable
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +# Default Secure Landing Zone Configuration
```suggestion
# Default Secure Landing Zone configuration
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## Pattern Variables
```suggestion
## Pattern variables
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Variables Available in Each Pattern
```suggestion
### Variables available in each pattern
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Variables for Patterns Including Virtual Servers
```suggestion
### Variables for patterns including virtual servers
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Variables for Patterns Including OpenShift Clusters
```suggestion
### Variables for patterns including OpenShift clusters
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## Resource Groups
```suggestion
## Resource groups
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## Cloud Services
```suggestion
## Cloud services
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Key Management
```suggestion
### Key management
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +#### Object Storage Buckets
```suggestion
#### Cloud Object Storage buckets
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +#### Object Storage API Keys
```suggestion
#### Cloud Object Storage API keys
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## VPC Infrastructure
```suggestion
## VPC infrastructure
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +#### Cluster Rules
```suggestion
#### Cluster rules
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +#### Management VPC Subnets
```suggestion
#### Management VPC subnets
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +#### Workload VPC Subnets
```suggestion
#### Workload VPC subnets
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Flow Logs
```suggestion
### Flow logs
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Virtual Private Endpoints
```suggestion
### Virtual private endpoints
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Default VPC Security Group
```suggestion
### Default VPC security group
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## Virtual Sever Deployments
```suggestion
## Virtual server deployments
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Boot Volume Encryption
```suggestion
### Boot volume encryption
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Virtual Server Profile
```suggestion
### Virtual server profile
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Additional Components
```suggestion
### Additional components
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +## OpenShift Cluster Deployments
```suggestion
## OpenShift cluster deployments
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Workers Per Zone
```suggestion
### Workers per zone
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +### Cluster Flavor
```suggestion
### Cluster flavor
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/mixed-pattern.md
> +# IBM Secure Landing Zone for Mixed Pattern
```suggestion
# IBM Secure Landing Zone for mixed pattern
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/mixed-pattern.md
> +## Artchitecture Diagram
```suggestion
## Architecture diagram
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/mixed-pattern.md
> +## Configured Components and Services
```suggestion
## Configured components and services
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/mixed-pattern.md
> +## Configured Components and Services
```suggestion
```

dupe heading

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/mixed-pattern.md
> +- Transit Gateway
```suggestion
- Resource groups
- Access groups
- Transit gateway
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/roks-pattern.md
> +# IBM Secure Landing Zone for IBM Cloud Red Hat OpenShift Kubernetes Pattern
```suggestion
# IBM Secure Landing Zone for IBM Cloud Red Hat OpenShift Kubernetes pattern
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/roks-pattern.md
> +## Artchitecture Diagram
```suggestion
## Architecture diagram
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/roks-pattern.md
> +## Configured Components and Services
```suggestion
## Configured components and services
```

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/roks-pattern.md
> +## Configured Components and Services
```suggestion
```
dupe

2022-10-05 21:41 UTC, SirSpidey commented on .docs/patterns/vsi-pattern.md
> +## Configured Components and Services
```suggestion
## Configured components and services
```

2022-10-06 09:46 UTC, vburckhardt commented on .docs/bastion/bastion.md
> +Secure Landing Zone can provision the implemented solution described in the following [document](https://cloud.ibm.com/docs/allowlist/framework-financial-services?topic=framework-financial-services-v
It's fine - all of the FSCloud thing been made public

2022-10-14 19:22 UTC, SirSpidey requested changes
found a few more small fixes

2022-10-14 19:22 UTC, SirSpidey commented on .docs/f5-big-ip/f5-big-ip.md
> +The F5 BIG-IP can be provisioned in the management or edge/transit VPC. In this case, use the edge/transit VPC. By default, it provisions an F5 BIG-IP within each zone of the region. You can change t
```suggestion
The F5 BIG-IP can be provisioned in the management or edge/transit VPC. In this case, use the edge/transit VPC. By default, it provisions an F5 BIG-IP within each zone of the region. You can change this setting in the [override.json](../../README.md#customizing-by-using-the-overridejson-file) file.
```

2022-10-14 19:22 UTC, SirSpidey commented on .docs/f5-big-ip/f5-big-ip.md
> +For more details about specifying input variables, see [Customizing your environment](../../README.md#using-terraform-input-variables). For more information about the F5 configuration variables, see
```suggestion
For more details about specifying input variables, see [Customizing your environment](../../README.md#customizing-your-environment). For more information about the F5 configuration variables, see the following documentation for the pattern:
```

2022-10-14 19:22 UTC, SirSpidey commented on README.md
> +Secure Landing Zone can set up a bastion host that uses Teleport. For more information, see [Provisioning a bastion host by using Teleport with Secure Landing Zone](.docs/bastion/bastion.md)
```suggestion
Secure Landing Zone can set up a bastion host that uses Teleport. For more information, see [Provisioning a bastion host by using Teleport with Secure Landing Zone](.docs/bastion/bastion.md).
```

2022-10-14 19:22 UTC, SirSpidey commented on README.md
> +This template supports creating any number of VPCs in a single region. The VPC network and components are created by the [Secure Landing Zone VPC module ](https://github.com/terraform-ibm-modules/ter
```suggestion
This template supports creating any number of VPCs in a single region. The VPC network and components are created by the [Secure Landing Zone VPC module](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc). The VPC components are described in the [main.tf](./main.tf) file.
```

2022-10-14 19:22 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +An [Activity Tracker](url-here) instance is provisioned for this architecture.
Not sure where this is supposed to link to.

2022-10-14 19:22 UTC, SirSpidey commented on .docs/pattern-defaults.md
> +Virtual Server components like additional block storage and Load Balancers can be configured using `override.json` and those variable definitions can be found in the [landing-zone module](../landing-
```suggestion
Virtual Server components, like additional block storage and load balancers, can be configured by using the `override.json` file. You can find the variable definitions in the [variables.tf](../variables.tf) file.
```

2022-10-17 12:27 UTC, SirSpidey approved these changes
Let's go!

2022-10-17 12:42 UTC, merged

2022-10-17 14:09 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v1.8.0)
- `v1.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: