Add example of very simple topology
terraform-ibm-modules/terraform-ibm-landing-zone pull request #206
Opened 2022-12-05 16:54 UTC by vburckhardt

### Description

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

2022-12-05 18:01 UTC, SirSpidey requested changes
Editorial suggestions

2022-12-05 18:01 UTC, SirSpidey commented on examples/one-vpc-one-vsi/README.md
> +   - Open Security Groups
```suggestion
1. A single VPC:
   - Named `management` in this example
   - Includes three subnets across the three availability zone to host VSIs
   - Default, open network ACLs
2. One single VSI:
   - Named 'jump-box' in this example
   - Located in one of the 'vsi' subnets of the VPC
   - Publicly exposed via a floating IP address.
   - Open security groups
```

2022-12-05 18:01 UTC, SirSpidey commented on examples/one-vpc-one-vsi/README.md
> +- Activity Tracker infrastructure (activity tracker route to an encrypted COS bucket storing audit events)
```suggestion
This example also creates the minimum encryption and audit infrastructure.
- A Key Protect instance and key that is used to encrypt the VSI boot volume
- The Activity Tracker infrastructure (Activity Tracker route to an encrypted COS bucket that stores audit events)
```

2022-12-06 13:09 UTC, SirSpidey approved these changes
I think both of the PRs need the pre-commit hook run locally to update the readme with the example.

2022-12-06 14:01 UTC, argeiger submitted a review, later dismissed

2022-12-06 21:38 UTC, SirSpidey approved these changes
👍

2022-12-08 16:02 UTC, merged

2022-12-08 20:28 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.12.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v1.12.0)
- `v1.12.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: