feat: consume latest vsi with additional variables
terraform-ibm-modules/terraform-ibm-landing-zone pull request #464
Opened 2023-06-12 09:29 UTC by rajatagarwal-ibm

### Description

Consumes latest VSI module with additional variables

### Types of changes in this PR

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-06-12 09:31 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-12 12:45 UTC, toddgiguere requested changes

2023-06-12 12:45 UTC, toddgiguere commented on variables.tf
> +      kms_encryption_enabled          = optional(bool)
These should be defaulted or override values from the pattern.

2023-06-14 14:08 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-15 07:34 UTC, rajatagarwal-ibm commented
Ran patterns/vsi and the boot volume is encrypted on the following settings.

```
kms_encryption_enabled        = true
skip_iam_authorization_policy = true
```

<img width="1421" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/108140212/3288e6cc-6a60-46e8-9566-16614a317223">

2023-06-15 09:33 UTC, vburckhardt approved these changes
lgtm

2023-06-15 10:22 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-15 12:35 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-15 15:13 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-19 21:00 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-23 11:32 UTC, rajatagarwal-ibm commented
/run pipeline

2023-06-23 13:39 UTC, ocofaigh approved these changes

2023-06-23 13:48 UTC, toddgiguere approved these changes

2023-06-23 13:55 UTC, merged