tests: add two schematics test
terraform-ibm-modules/terraform-ibm-landing-zone pull request #587
Opened 2023-09-27 12:56 UTC by jor2

### Description
Added schematics test for two other tests in pr_test.go

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-09-27 16:46 UTC, ocofaigh requested changes
see comments

2023-09-27 16:46 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "ssh_key", Value: sshPublicKey(t), DataType: "string"},
An ssh key should only be passed to the VSI and VSI quickstart patterns. For VSI standard, the var name is `ssh_public_key` and for quickstart it is `ssh_key`

2023-09-27 16:46 UTC, ocofaigh commented on tests/pr_test.go
> +}
Missing `TestRunVPCPatternSchematics` which should replace the `TestRunVpcPattern` test

2023-09-27 16:46 UTC, ocofaigh commented on tests/pr_test.go
> +	options := setupOptionsSchematics(t, "rok-sc", vsiPatternTerraformDir)
`rok-sc` -> `vsi-sc`

2023-09-27 16:46 UTC, ocofaigh commented on tests/pr_test.go
> +func TestRunQuickStartPatternSchematics(t *testing.T) {
`TestRunQuickStartPatternSchematics` -> `TestRunVSIQuickStartPatternSchematics`

2023-09-27 16:46 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "region", Value: options.Region, DataType: "string"},
can you set `add_atracker_route` to `false` here please?

2023-09-29 11:43 UTC, ocofaigh commented
/run pipeline

2023-09-29 16:02 UTC, ocofaigh commented
Looks like some backend issue `The system is currently unable to fulfill the request. Please retry. If the failure persists, contact support and provide the trace value from this error.`

Retrying..

2023-09-29 16:02 UTC, ocofaigh commented
/run pipeline

2023-10-01 18:10 UTC, jor2 commented
/run pipeline

2023-10-04 08:22 UTC, ocofaigh commented
/run pipeline

2023-10-04 11:30 UTC, ocofaigh commented
`TestRunUpgradeRoksPattern` failed with a timeout when provisioning VPN gateway: `timeout while waiting for state to become 'done, ' (last state: 'provisioning', timeout: 10m0s)`

`TestRunRoksPatternSchematics` failed in the schematics destroy, however the destroy actually passed. I saw the same thing yesterday and have reported to schematics team

`TestRunVSIQuickStartPatternSchematics` failed on apply with `Error: cannot add more than 5 gateways to the selected region` - @toddgiguere Is the schematics tests also selecting a region based on VPC availability? I wonder should we disable transit gateway for all but one of of tests for SLZ?

2023-10-04 13:10 UTC, toddgiguere commented
@ocofaigh The tests are using region selection correctly, however they are all running in parallel and we are not using a shared cloudInfoService, so my guess is that with the timing they are all selecting the same region.

If we have some limitations then we should probably adjust to using a shared cloudInfo so that different regions are selected for all tests.

@jor2 I can explain how this works if needed.

2023-10-04 15:22 UTC, jor2 commented
/run pipeline

2023-10-04 17:22 UTC, jor2 commented
> @ocofaigh The tests are using region selection correctly, however they are all running in parallel and we are not using a shared cloudInfoService, so my guess is that with the timing they are all selecting the same region.
> 
> 
> 
> If we have some limitations then we should probably adjust to using a shared cloudInfo so that different regions are selected for all tests.
> 
> 
> 
> @jor2 I can explain how this works if needed.

Fixed worked, thanks :)

2023-10-05 08:16 UTC, ocofaigh approved these changes

2023-10-05 08:16 UTC, merged

2023-10-06 14:53 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v4.13.0)
- `v4.13.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: