[DO NOT MERGE] onboard vsi extension to catalog
terraform-ibm-modules/terraform-ibm-landing-zone pull request #610
Opened 2023-10-25 15:24 UTC by ocofaigh

### Description

onboard vsi extension to catalog
TODO: - Add a prereq script to deploy a VPC before doing catalog validation

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-10-25 15:25 UTC, ocofaigh commented
Still work to do in this PR, but @SirSpidey looking for early feedback around naming here

2023-10-25 19:20 UTC, SirSpidey commented
@ocofaigh some ideas based on how I assume this will display to users

### variation name

**Original**
- "label": "VSI on existing VPC"

**Suggested**
- "label": "Existing VPC" 

**Alternatives**
- Extend VPC with VSI
- Add VSI to VPC

#### Catalog
<img width="933" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/8194208/873a3556-bd13-40c2-b6d1-96a9b14a1e0d">


#### Deployment guide
<img width="272" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/8194208/d2b52ea5-6071-42a7-b324-a6184ab82bbc">

2023-10-26 09:37 UTC, ocofaigh commented
Thanks @SirSpidey I have updated to "Existing VPC"

2023-10-26 12:16 UTC, SirSpidey commented
@ocofaigh Do we want more feedback on this first extension? (To find out whether the label is clear.) Of course, we should add details in the description under _Learn more_. (And in the deployment guide.)

2023-10-26 16:12 UTC, SirSpidey commented
@ocofaigh Keith confirms that the dropdown mockup is the way this will get displayed. So I guess the name is irrelevant. The UI will display `Extend VSI on VPC landing zone` in the dropdown. When you click **Extend**, only the standard variation/flavor tile will remain, assuming that’s the prereq (quickstart tile will disappear).

2023-12-07 13:13 UTC, ocofaigh commented
More updates needed in this PR.. working on them now..

2023-12-07 14:30 UTC, SirSpidey requested changes
Reviewed only from line 499

I think we need to modify the overview in both this json and extension readme file. 

The statements here assume that you have already deployed a DA, which I think is the workflow.

`The block storage to KMS auth policy must exist. This policy would have been created by one of the above deployable architectures if the add_kms_block_storage_s2s variable was set to true, which is default value.`

Suggestion
- You need an authorization policy that grants access between block storage and the KMS. The policy exists if you set the `add_kms_block_storage_s2s` input variable to `true` (the default value) in your existing landing zone deployable architecture.

---

`You need the VPC ID, subnet names, and boot volume encryption key from your existing landing zone VPC deployable architecture. For information about finding these values, see [Adding a VSI to your VPC landing zone deployable architecture](https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-ext-with-vsi).`

Suggestion
- You need the VPC ID, subnet names, and boot volume encryption key from your existing landing zone deployable architecture. For information about finding these values, see [Adding a VSI to your VPC landing zone deployable architecture](https://cloud.ibm.com/docs/secure-infrastructure-vpc?topic=secure-infrastructure-vpc-ext-with-vsi).

2023-12-07 14:30 UTC, SirSpidey commented on ibm_catalog.json
> +            "descriptions": "This architecture creates virtual server instances (VSI) for VPC in some or all of the subnets of any existing landing zone VPC deployable architecture.\r\n\r\n## Before
see notes in review comments

2023-12-07 14:30 UTC, SirSpidey commented on ibm_catalog.json
> +                "title": "Virtual Server Instances for every subnet",
```suggestion
                "title": "Adds a virtual server instance in every VPC subnet",
```

2023-12-07 14:30 UTC, SirSpidey commented on ibm_catalog.json
> +                "title": "Uses Floating IP address for access through the public internet",
```suggestion
                "title": "Uses floating IP addresses for access through the public internet",
```

2023-12-07 14:30 UTC, SirSpidey commented on ibm_catalog.json
> +                "description": "The VSI on existing VPC deployable architecture extension is based on the IBM Cloud for Financial Services reference architecture. The architecture creates a customiza
```suggestion
                "description": "The extension to an existing VPC deployable architecture is based on the IBM Cloud for Financial Services reference architecture. The architecture creates a customizable and secure infrastructure with virtual servers to run your workloads with IBM Cloud VPC in multizone regions."
```

2023-12-07 14:31 UTC, ocofaigh commented
Thanks for the feedback @SirSpidey - I robbed that text from other variations in this json already so Ill have to update those too to be consistent

2023-12-07 20:56 UTC, SirSpidey commented
> Thanks for the feedback @SirSpidey - I robbed that text from other variations in this json already so Ill have to update those too to be consistent

@ocofaigh Feel free to delegate that to me.

2023-12-08 10:19 UTC, ocofaigh commented
@SirSpidey I've made the changes locally. Working on other changes now so will be included in my next commit

2023-12-08 16:37 UTC, SirSpidey commented on patterns/vsi-extension/README.md
> +
```suggestion
This architecture creates virtual server instances (VSI) in some or all of the subnets of one VPC of an existing landing zone deployable architecture. To create VSIs in multiple VPCs, deploy the extension once for each VPC.
```
suggestion to pull it all together

2023-12-11 17:18 UTC, ocofaigh commented
The prereq script is working well now. I was able to import a version to catalog, however its not displaying. Some issue with the extension type. The catalog team are debugging now

2023-12-12 09:51 UTC, ocofaigh commented
Need to wait until https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/648 is merged first and then I'll rebase this PR and kick off pipeline

2023-12-12 10:48 UTC, Aashiq-J approved these changes
LGTM

2023-12-12 15:21 UTC, ocofaigh commented
/run pipeline

2023-12-12 18:05 UTC, merged