feat: expose secondary_storage
terraform-ibm-modules/terraform-ibm-landing-zone pull request #691
Opened 2024-01-29 02:13 UTC by jor2

### Description

Surface the secondary storage field https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#secondary_storage in landing zone interface (via override.json).

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/688

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Surface the secondary storage field https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#secondary_storage in landing zone interface (via override.json).

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-29 02:15 UTC, jor2 commented
/run pipeline

2024-01-29 04:19 UTC, jor2 commented
/run pipeline

2024-01-29 08:45 UTC, ocofaigh commented
@jor2 FYI pipeline is blocked due to a backend bug - we are working on a workaround to ignore the error in our tests to unblock PRs as backend fix won't be in prod for 2-3 weeks

2024-01-29 09:21 UTC, ocofaigh requested changes
@jor2 I left some comments. BTW, is there no test for the override json example? I see the test `TestRunOverride` is actually running the VSI QS pattern and I wonder is that a mistake?

2024-01-29 09:21 UTC, ocofaigh commented on patterns/roks/module/variables.tf
> +  description = "Secondary storage type for cluster. Use the IBM Cloud CLI command `ibmcloud ks flavors` to find valid machine types, e.g `ibmcloud ks flavor get --flavor bx2.16x64 --provider vpc-gen
Optionally specify a secondary storage option to attach to all cluster worker nodes. This value is immutable and can't be changed after provisioning. Use the IBM Cloud CLI command `ibmcloud ks flavors` to find valid options, e.g `ibmcloud ks flavor get --flavor bx2.16x64 --provider vpc-gen2 --zone us-south-1`.

2024-01-29 09:21 UTC, ocofaigh commented on patterns/mixed/variables.tf
> +  description = "Secondary storage type for cluster. Use the IBM Cloud CLI command `ibmcloud ks flavors` to find valid machine types, e.g `ibmcloud ks flavor get --flavor bx2.16x64 --provider vpc-gen
Optionally specify a secondary storage option to attach to all cluster worker nodes. This value is immutable and can't be changed after provisioning. Use the IBM Cloud CLI command `ibmcloud ks flavors` to find valid options, e.g `ibmcloud ks flavor get --flavor bx2.16x64 --provider vpc-gen2 --zone us-south-1`.

2024-01-29 09:21 UTC, ocofaigh commented on examples/override-example/override.json
> +"enable_transit_gateway": true,
indentation looks wrong here?

2024-01-29 09:21 UTC, ocofaigh commented on examples/override-example/override.json
> +  "clusters": [
you should update this example readme since it now looks like it will deploy a cluster

2024-01-29 09:41 UTC, jor2 commented on tests/pr_test.go
> +const overrideExampleTerraformDir = "examples/override-example"
I was going to add an override test, but there seems to be whole lot of tests running and wasn't sure if we wanted to add more.

2024-01-29 10:07 UTC, ocofaigh commented on tests/pr_test.go
> +const overrideExampleTerraformDir = "examples/override-example"
Every example should have a test - so we need to decide if the test is in pr_test.go, or other_test.go. Suggest you create a follow up issue to track the test creation. Keep it in a separate PR to this.

2024-01-30 19:35 UTC, merged

2024-01-30 19:37 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 5.13.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.13.0)
- `v5.13.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: