tests: add new test for override example
terraform-ibm-modules/terraform-ibm-landing-zone pull request #694
Opened 2024-01-31 11:35 UTC by jor2

### Description

Test for override example in landing zone.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Test the override example in other_tests.go.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-31 12:05 UTC, jor2 commented
/run pipeline

2024-01-31 15:54 UTC, jor2 commented
/run pipeline

2024-01-31 19:43 UTC, toddgiguere requested changes
I think this test is a duplicate of this one that already exists?
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/tests/pr_test.go#L308

Also this particular test is not really doing anything, I think what it was meant to do is use the `config` output from first  apply as the override for the second apply? But setting that override doesn't take place in this test.

2024-01-31 19:52 UTC, toddgiguere requested changes

2024-01-31 19:52 UTC, toddgiguere commented on tests/other_test.go
> +		planStruct, planErr := terraform.InitAndPlanAndShowWithStructE(options.Testing, options.TerraformOptions)
RunTestConsistency() will already run an Apply and then follow it up with a "InitAndPlan" to verify idempotent. I'm not sure what a second "InitAndPlan" will do here?

2024-02-02 01:14 UTC, jor2 commented
> I think this test is a duplicate of this one that already exists? https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/tests/pr_test.go#L308
> 
> Also this particular test is not really doing anything, I think what it was meant to do is use the `config` output from first apply as the override for the second apply? But setting that override doesn't take place in this test.

That test runs the `quickStartPatternTerraformDir` and does that weird overriding using previous tests output. Should I replace that test with this one?

2024-02-02 12:20 UTC, jor2 commented
/run pipeline

2024-02-02 13:11 UTC, toddgiguere approved these changes
I see the difference now, the other override test I was referring to is more of a "config output" test, and using override. This test is just testing our new example, so I do not think there is an overlap.

2024-02-06 13:07 UTC, ocofaigh commented
/run pipeline

2024-02-06 15:08 UTC, merged

2024-02-06 20:03 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 5.15.1 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.15.1)
- `v5.15.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: