feat: add support for ocp 4.15
terraform-ibm-modules/terraform-ibm-landing-zone pull request #782
Opened 2024-05-03 19:26 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-03 19:26 UTC, Aashiq-J commented
/run pipeline

2024-05-03 19:31 UTC, ocofaigh requested changes
see comments

2024-05-03 19:31 UTC, ocofaigh commented on patterns/roks/variables.tf
> +  description = "Whether to allow public outbound access from the cluster workers. This is only applicable for `ocp_version` 4.15"
hmm, `ocp_version` is not the variable name for SLZ. Maybe use English here and say "Red Hat OpenShift 4.15"

2024-05-03 19:31 UTC, ocofaigh commented on ibm_catalog.json
> +                  "value": "4.15_openshift"
I think update the `default_value` to 4.15 so the tests will run it. We won't release it to prod for another month, so if there are issues, plenty of time to debug

2024-05-03 19:31 UTC, ocofaigh commented on patterns/roks/module/variables.tf
> +  description = "Whether to allow public outbound access from the cluster workers. This is only applicable for `ocp_version` 4.15"
hmm, `ocp_version` is not the variable name for SLZ. Maybe use English here and say "Red Hat OpenShift 4.15"

2024-05-07 04:20 UTC, Aashiq-J commented
/run pipeline

2024-05-07 08:12 UTC, Aashiq-J commented
/run pipeline

2024-05-14 14:04 UTC, ocofaigh approved these changes

2024-05-14 16:20 UTC, ocofaigh commented
/run pipeline

2024-05-15 05:07 UTC, Aashiq-J commented
```
2024-05-14T16:52:14.6911615Z     destroy.go:11: 
2024-05-14T16:52:14.6912497Z         	Error Trace:	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.13/modules/terraform/destroy.go:11
2024-05-14T16:52:14.6913766Z         	            				/__w/terraform-ibm-landing-zone/terraform-ibm-landing-zone/tests/pr_test.go:509
2024-05-14T16:52:14.6914606Z         	Error:      	Received unexpected error:
2024-05-14T16:52:14.6915506Z         	            	FatalError{Underlying: error while running command: exit status 1; [31m╷[0m[0m
2024-05-14T16:52:14.6917244Z         	            	[31m│[0m [0m[1m[31mError: [0m[0m[1mtimeout while waiting for state to become 'done, failed' (last state: 'deleting', timeout: 10m0s)[0m
2024-05-14T16:52:14.6918332Z         	            	[31m│[0m [0m
2024-05-14T16:52:14.6918778Z         	            	[31m│[0m [0m[0m
2024-05-14T16:52:14.6919153Z         	            	[31m╵[0m[0m}
2024-05-14T16:52:14.6919577Z         	Test:       	TestRunVsiExtention
2024-05-14T16:52:14.6920011Z --- FAIL: TestRunVsiExtention (1243.28s)
```
Error not related to this PR change.
Retrying..

2024-05-15 05:07 UTC, Aashiq-J commented
/run pipeline

2024-05-15 06:59 UTC, Aashiq-J commented
/run pipeline

2024-05-15 09:40 UTC, ocofaigh commented
@Aashiq-J The tests are going to fail due to known issue with destroy - since its unrelated to your changes, the since the OCP tests passed, I'm going to force merge this PR

2024-05-15 09:41 UTC, merged

2024-05-15 09:42 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 5.22.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.22.0)
- `v5.22.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: