fix(deps): update base-ocp to 3.34.0
terraform-ibm-modules/terraform-ibm-landing-zone pull request #905
Opened 2024-10-21 05:13 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-10-21 12:01 UTC, ocofaigh commented
@Aashiq-J you able to check why pipeline failed?

2024-10-22 03:08 UTC, Aashiq-J commented
/run pipeline

2024-10-22 12:35 UTC, toddgiguere requested changes

2024-10-22 12:35 UTC, toddgiguere commented on variables.tf
> +            operating_system     = string                # The operating system of the workers in the default worker pool. See https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions#
I'm  worried about some teams that call this root level directly, and we are changing this from optional to required. Would it make sense to keep this as optional but with default of REDHAT_8_64? `optional(string, "REDHAT_8_64")`

2024-10-23 12:57 UTC, toddgiguere approved these changes

2024-10-23 13:49 UTC, merged