feat: add migration scripts
terraform-ibm-modules/terraform-ibm-landing-zone pull request #938
Opened 2024-12-18 04:09 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2025-01-28 16:58 UTC, ocofaigh submitted a review, later dismissed

2025-01-28 16:58 UTC, ocofaigh commented
/run pipeline

2025-01-29 04:26 UTC, Aashiq-J commented
/run pipeline

2025-01-29 09:16 UTC, ocofaigh commented
/run pipeline

2025-01-29 09:50 UTC, Aashiq-J commented
/run pipeline

2025-01-29 12:04 UTC, ocofaigh requested changes
@Aashiq-J I don't think we should add 4.17 as the default yet. 4.16 is still the default IKS have:
![image](https://github.com/user-attachments/assets/ba3905b8-7092-459b-ba6c-ab8730166273)

We also need to remove support for 4.12 and 4.13 as IKS do not support them either

2025-01-29 12:42 UTC, Aashiq-J commented
/run pipeline

2025-01-29 12:59 UTC, ocofaigh approved these changes

2025-01-29 15:28 UTC, Aashiq-J commented
```
2025-01-29T13:26:55.4887073Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0m'.terraform/modules/landing_zone.landing_zone.cluster/scripts/reset_iks_api_key.sh
2025-01-29T13:26:55.4888530Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mus-south 078eeb823453417d9fe5a6709035b46b false default': exit status 1.
2025-01-29T13:26:55.4889622Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mOutput: ERROR:: FAILED TO RESET THE IAM API KEY
2025-01-29T13:26:55.4890422Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mHTTP/2 200 
2025-01-29T13:26:55.4891147Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mcontent-length: 60
2025-01-29T13:26:55.4892088Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mcontent-type: application/json; charset=utf-8
2025-01-29T13:26:55.4893180Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mcross-origin-resource-policy: cross-origin
2025-01-29T13:26:55.4894020Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-carrier: prod-dal10-carrier105
2025-01-29T13:26:55.4894901Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-correlation-id: 623de347-c900-444c-9a70-f94ddebc6d0c
2025-01-29T13:26:55.4895776Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-hostname: armada-api-5c78449d49-dqhkd
2025-01-29T13:26:55.4896562Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-region: us-south
2025-01-29T13:26:55.4897378Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-request-id: fcf10023-90ef-4724-823a-0da60f0aa118
2025-01-29T13:26:55.4898323Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mcontent-security-policy: default-src 'none'; script-src 'self'
2025-01-29T13:26:55.4899314Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0m'unsafe-inline' 'unsafe-eval'; connect-src 'self'; img-src 'self' data:;
2025-01-29T13:26:55.4900384Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mstyle-src 'self' 'unsafe-inline'; font-src 'self'
2025-01-29T13:26:55.4901316Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mstrict-transport-security: max-age=31536000; includeSubDomains
2025-01-29T13:26:55.4902206Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-content-type-options: nosniff
2025-01-29T13:26:55.4903218Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-frame-options: DENY
2025-01-29T13:26:55.4904068Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-permitted-cross-domain-policies: master-only
2025-01-29T13:26:55.4904902Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mx-xss-protection: 1; mode=block
2025-01-29T13:26:55.4905708Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mexpires: Wed, 29 Jan 2025 13:24:32 GMT
2025-01-29T13:26:55.4906548Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mcache-control: max-age=0, no-cache, no-store
2025-01-29T13:26:55.4907328Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mpragma: no-cache
2025-01-29T13:26:55.4908185Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mdate: Wed, 29 Jan 2025 13:24:32 GMT
2025-01-29T13:26:55.4908987Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mserver-timing: cdn-cache; desc=MISS
2025-01-29T13:26:55.4909782Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mserver-timing: edge; dur=192
2025-01-29T13:26:55.4910570Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mserver-timing: origin; dur=729
2025-01-29T13:26:55.4911336Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mserver-timing: ak_p;
2025-01-29T13:26:55.4912437Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0mdesc="1738157071872_400321306_82126495_94558_5877_5_41_15";dur=1
2025-01-29T13:26:55.4913377Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0m
2025-01-29T13:26:55.4914192Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0m{"apiKeyUUID":"ApiKey-99d6e65d-34e8-4636-b778-60942b012c90"}
2025-01-29T13:26:55.4915046Z TestRunUpgradeROKSQuickStartPattern 2025-01-29T13:26:55Z logger.go:67: [31m│[0m [0m
```

ROKS upgrade tests are failing because the main branch has the old code which doesn't support status 200 for reset apikey.

2025-01-29 15:44 UTC, ocofaigh commented
I'm going to force merge this PR since the other tests passed, and its expected for the upgrade test to fail until that breaking apichange it fixed

2025-01-29 15:45 UTC, merged

2025-01-29 15:46 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 6.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v6.8.0)
- `v6.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: